### PR TITLE
docs: update PHP & Laravel documentation

### PR DESCRIPTION
**Pull request by repat**
## Summary

Recent changes I made in the PHP-Client and Laravel Bridge need to be updated here, mainly:

* `ARK` -> `Ark` (Laravel bridge)
* Fixing return types (both)

### Related PRs

- https://github.com/ArkEcosystem/laravel/pull/28
- https://github.com/ArkEcosystem/php-client/pull/95

## Checklist

- [x] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A collaborator has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A collaborator has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $20 USD._

**Pull request merged**
